blueprint:
  name: "Set Circadian Lights State"
  description: "This script sets a group of lights to a set state based on the selected circadian scene."
  domain: script
  author: "Cody James"

  input:
    lifx_color_1000_bulbs:
      name: "LIFX Color 1000 Bulbs"
      description: "Select the bulbs to effect."
      default: {}
      selector:
        device:
          filter:
            - model: "A19 US"
          multiple: true
    lifx_br30_bulbs:
      name: "LIFX BR30 Bulbs"
      description: "Select the bulbs to effect."
      default: {}
      selector:
        device:
          filter:
            - model: "BR30"
          multiple: true

    lifx_mini_color_bulbs:
      name: "Mini Color Bulbs"
      description: "Select the bulbs to effect."
      default: {}
      selector:
        device:
          filter:
            - model: "Color"
          multiple: true

    lifx_mini_ctt_bulbs:
      name: "Mini CTT Bulbs"
      description: "Select the bulbs to effect."
      default: {}
      selector:
        device:
          filter:
            - model: "Mini White to Warm"
          multiple: true
    hue_gu10_bulbs:
      name: "Hue GU10 Bulbs"
      description: "Select the bulbs to effect."
      default: {}
      selector:
        device:
          filter:
            - model: "LTG001"
          multiple: true
    other_actions:
      name: "Other Actions"
      default: {}
      selector:
        action:
variables:
    light_presets:
      lifx_color-1000:
        #Kelvin
        kelvin_morning: 9000
        kelvin_eventing: 4000
        kelvin_night: 2500
        kelvin_bs1: 1900
        kelvin_bs2: 1900
        kelvin_bs3: 1500

        #Brightness
        brightness_morning: 80
        brightness_eventing: 80
        brightness_night: 60
        brightness_bs1: 30
        brightness_bs2: 10
        brightness_bs3: 1

      lifx_br30:
        #Kelvin
        kelvin_morning: 9000
        kelvin_eventing: 4000
        kelvin_night: 2500
        kelvin_bs1: 1900
        kelvin_bs2: 1900
        kelvin_bs3: 1500

        #Brightness
        brightness_morning: 100
        brightness_eventing: 80
        brightness_night: 70
        brightness_bs1: 40
        brightness_bs2: 15
        brightness_bs3: 1

      lifx_mini-color:
        #Kelvin
        kelvin_morning: 9000
        kelvin_eventing: 4000
        kelvin_night: 2500
        kelvin_bs1: 1900
        kelvin_bs2: 1900
        kelvin_bs3: 1500

        #Brightness
        brightness_morning: 100
        brightness_eventing: 100
        brightness_night: 100
        brightness_bs1: 50
        brightness_bs2: 25
        brightness_bs3: 1

      lifx_mini-ctt:
        #Kelvin
        kelvin_morning: 5700
        kelvin_eventing: 4000
        kelvin_night: 3000
        kelvin_bs1: 2400
        kelvin_bs2: 2400
        kelvin_bs3: 2400

        #Brightness
        brightness_morning: 100
        brightness_eventing: 100
        brightness_night: 100
        brightness_bs1: 60
        brightness_bs2: 30
        brightness_bs3: 1

      hue_gu10:
        #Kelvin
        kelvin_morning: 5700
        kelvin_eventing: 4000
        kelvin_night: 3000
        kelvin_bs1: 2400
        kelvin_bs2: 2400
        kelvin_bs3: 2400

        #Brightness
        brightness_morning: 100
        brightness_eventing: 100
        brightness_night: 100
        brightness_bs1: 78
        brightness_bs2: 39
        brightness_bs3: 1

sequence:
  "{{!input other_ations}}"