blueprint:
  name: Lifx Set Default Blueprint
  description: >-
    Set lifx lights to default settings
  domain: script
  input:
    brightness_morning:
      name: Morning Brightness
      description: The brightness percentage to set the lights to
    brightness_evening:
      name: Eventing Brightness
      description: The brightness percentage to set the lights to
    brightness_night:
      name: Night Brightness
      description: The brightness percentage to set the lights to
    brightness_bs1:
      name: Bed Stage One Brightness
      description: The brightness percentage to set the lights to
    brightness_bs2:
      name: Bed Stage Two Brightness
      description: The brightness percentage to set the lights to
    brightness_bs3:
      name: Bed Stage Three Brightness
      description: The brightness percentage to set the lights to
    kelvin_morning:
      name: Morning kelvin
      description: The kelvin to set the lights to
    kelvin_evening:
      name: Eventing kelvin
      description: The kelvin to set the lights to
    kelvin_night:
      name: Night kelvin
      description: The kelvin to set the lights to
    kelvin_bs1:
      name: Bed Stage One kelvin
      description: The kelvin to set the lights to
    kelvin_bs2:
      name: Bed Stage Two kelvin
      description: The kelvin to set the lights to
    kelvin_bs3:
      name: Bed Stage Three kelvin
      description: The kelvin to set the lights to
    transition_default:
      name: Default Transition
      description: The default transition
    transition_morning:
      name: Morning transition
      description: The transition to set the lights to
    transition_evening:
      name: Eventing transition
      description: The transition to set the lights to
    transition_night:
      name: Night transition
      description: The transition to set the lights to
    transition_bs1:
      name: Bed Stage One transition
      description: The transition to set the lights to
    transition_bs2:
      name: Bed Stage Two transition
      description: The transition to set the lights to
    transition_bs3:
      name: Bed Stage Three transition
      description: The transition to set the lights to
    
mode: parallel
variables:
  ease: false
  scene: 
  lights:
  turn_on: true
fields:
  scene:
    name: "Scene to Set"
    description: "The scene to set in the room."
    required: true
    default: "Morning"
    example: "Morning"
    advanced: false
    selector:
      select:
        options:
          - "Morning"
          - "Evening"
          - "Night"
          - "Bed Stage One"
          - "Bed Stage Two"
          - "Bed Stage Three"
  ease:
    name: "Ease Lights to New Scene"
    description: "Ease the lights to the new scene over a few minutes."
    required: false
    default: false
    example: "false"
    advanced: false
    selector:
      boolean:
  lights:
    name: "Lights to change"
    description: "List of lights to set in this operation"
    required: true
    default: ''
    example: "light.kitchen_lights"
    advanced: false
    selector:
      entity:

  turn_on:
    name: "Turn On Lights"
    description: "Turn on the lights when setting values"
    required: true
    default: true
    example: 'true'
    selector:
      boolean:
sequence:
- choose:
  - conditions:
    - condition: template
      value_template: "{{ turn_on == true }}"
    sequence:
      - service: lifx.set_state
        target: 
          entity_id: "{{lights}}"
        data_template:
          power: true
          brightness_pct: >
            {% if (scene == 'Morning') %}
            100
            {% elif (scene == 'Evening') %}
            100
            {% elif (scene == 'Night') %}
            100
            {% elif (scene == 'Bed Stage One') %}
            50
            {% elif (scene == 'Bed Stage Two') %}
            25
            {% elif (scene == 'Bed Stage Three') %}
            1
            {% endif %}
          kelvin: >
            {% if (scene == 'Morning') %}
            9000
            {% elif (scene == 'Evening') %}
            4000
            {% elif (scene == 'Night') %}
            2500
            {% elif (scene == 'Bed Stage One') %}
            1900
            {% elif (scene == 'Bed Stage Two') %}
            1900
            {% elif (scene == 'Bed Stage Three') %}
            1500
            {% endif %}
          transition: >
            {% if (ease is not defined) or (ease == false) %}
            1
            {% elif (ease == true) and (scene == 'Morning') %}
            600
            {% elif (ease == true) and (scene == 'Evening') %}
            120
            {% elif (ease == true) and (scene == 'Night') %}
            300
            {% elif (ease == true) and (scene == 'Bed Stage One') %}
            300
            {% elif (ease == true) and (scene == 'Bed Stage Two') %}
            300
            {% elif (ease == true) and (scene == 'Bed Stage Three') %}
            300
            {% endif %}

  - conditions:
    - condition: template
      value_template: "{{ turn_on == false }}"
  sequence:
      - service: lifx.set_state
        target: 
          entity_id: "{{lights}}"
        data_template:
          brightness_pct: >
            {% if (scene == 'Morning') %}
            100
            {% elif (scene == 'Evening') %}
            100
            {% elif (scene == 'Night') %}
            100
            {% elif (scene == 'Bed Stage One') %}
            50
            {% elif (scene == 'Bed Stage Two') %}
            25
            {% elif (scene == 'Bed Stage Three') %}
            1
            {% endif %}
          kelvin: >
            {% if (scene == 'Morning') %}
            9000
            {% elif (scene == 'Evening') %}
            4000
            {% elif (scene == 'Night') %}
            2500
            {% elif (scene == 'Bed Stage One') %}
            1900
            {% elif (scene == 'Bed Stage Two') %}
            1900
            {% elif (scene == 'Bed Stage Three') %}
            1500
            {% endif %}
          transition: >
            {% if (ease is not defined) or (ease == false) %}
            1
            {% elif (ease == true) and (scene == 'Morning') %}
            600
            {% elif (ease == true) and (scene == 'Evening') %}
            120
            {% elif (ease == true) and (scene == 'Night') %}
            300
            {% elif (ease == true) and (scene == 'Bed Stage One') %}
            300
            {% elif (ease == true) and (scene == 'Bed Stage Two') %}
            300
            {% elif (ease == true) and (scene == 'Bed Stage Three') %}
            300
            {% endif %}