blueprint:
  name: Light Circadian Transition WLED Preset
  description: Set lights to default settings for time of day using WLED presets.
  domain: script
  input:
    preset_select: 
      name: Lights
      default: {}
      selector: 
        entity:
          domain: input_select
mode: parallel
variables:
  ease: false
  scene: 
  preset_select: !input 'preset_select'

fields:
  scene:
    name: Preset Name
    description: The preset to set on the WLED light.
    required: true
    default: Morning
    example: Morning
    advanced: false
    selector:
      select:
        options:
        - Morning
        - Evening
        - Night
        - Bed Stage One
        - Bed Stage Two
        - Bed Stage Three
  ease:
    name: Ease Into Scene
    description: Ease the lights to the new scene over a few minutes.
    required: true
    default: false
    example: "false"
    advanced: false
    selector:
      boolean:
  preset_select:
    name: Preset Select
    description: input_select to use for the light
    required: true
    example: input_select.bedside_lights_preset
    advanced: false
    selector:
      target:
        entity:
          domain: input_select
sequence:
- service: input_select.select_option
  target: 
    entity_id: "{{preset_select}}"
  data_template:
    option: "{{scene}}"